### ISSUE TITLE
Viewing categories for clients

### ISSUE THREAD

**Issue by ApokalmiX** [ignacionelson/ProjectSend#556]
Hello,

I would like my clients to be able to see the category tree instead of the list of files when they connect (Like the filter combobox).
The amount of file to download on the main page makes it unusable.
Is it possible to make this optional?

Best regards

**Comment by gaspolo** [comment]
u need to change this : 
------------------------------------------
 if ($this->user_level == '0') {        
                                                $results['location']       = BASE_URI."my_files/";
-------------------------------------------
in:
-------------------------------------------
 if ($this->user_level == '0') {
                                                $results['location']       = BASE_URI."categories.php";
--------------------------------------------

the file is: process.php

so when the user login , the "home" page will be http://xxxxxxx/categories.php

**Comment by ignacionelson** [comment]
Hello! What template are you using?
Both gallery and pinboxes are being updated to have pagination which should fix the issue with long lists of files.
On "gallery", the category selector will also be added soon.

**Comment by liberaxpress** [comment]
I notice this has still not been added in development?,
I don't see the point of being able to add a category and sub-category when uploading files, then the client has to go through 100's of files to search for files in the category, 
I spent 2 hours uploading files and added them in own categories depending on the type of file for my clients to access and it just shows 154 files in 1 category, even changing it to pin boxes is no good.. if you have 2 sub-categories of same name in 2 different categories it doesn't say from which category they are from!
Surely it is easy for you to add a simple script so the drop down menu at the top of client access page defines each category & sub-category instead of a All Categories Filter only?
Or am I missing something?

**Comment by liberaxpress** [comment]
What I mean is I added 6 categories when uploading files, then in each category I added 3-4 more sub-categories and uploaded files to each depending on type - e.g.
Setup guides-mbox setup->how to
Setup guides->gbox setup->how to
Now I have 2x how to guides but client doesn't know until they are open which it is for, and even if I renamed them I have other help files associated that should have been in same sub-category and now I have to go and rename over 100 files,
Can this be done or do I need to find a different tool that gives me the sub-category feature that I need?

**Comment by ignacionelson** [comment]
This issue is being closed as part of a bulk cleanup. ProjectSend has undergone significant changes since this was reported (including r1720 and r1994), and many older issues no longer apply to the current codebase.

If you are still experiencing this problem on the latest version, please open a new issue with updated details and we'll be happy to look into it. Thank you for your contribution!
